create extension if not exists pgcrypto;

create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, target_exam text, target_level text, role text not null default 'student', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.questions (id uuid primary key default gen_random_uuid(), exam text not null default 'TEF', skill text not null, level text not null, prompt text not null, passage text, options jsonb not null default '[]'::jsonb, correct_answer text, explanation text, source text not null default 'ARPREE', is_published boolean not null default true, created_at timestamptz not null default now());
create table if not exists public.attempts (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, exam text not null, skill text not null, level text not null, total_questions integer not null default 0, correct_answers integer not null default 0, score_percent numeric(5,2) not null default 0, started_at timestamptz not null default now(), completed_at timestamptz);
create table if not exists public.attempt_answers (id uuid primary key default gen_random_uuid(), attempt_id uuid not null references public.attempts(id) on delete cascade, question_id uuid not null references public.questions(id) on delete restrict, selected_answer text, is_correct boolean not null default false, answered_at timestamptz not null default now(), unique(attempt_id, question_id));
create index if not exists questions_filters_idx on public.questions(exam, skill, level, is_published);
create index if not exists attempts_user_idx on public.attempts(user_id, completed_at desc);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,full_name) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',new.email)) on conflict(id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.questions enable row level security;
alter table public.attempts enable row level security;
alter table public.attempt_answers enable row level security;
drop policy if exists profiles_own on public.profiles; create policy profiles_own on public.profiles for all using(auth.uid()=id) with check(auth.uid()=id);
drop policy if exists questions_read on public.questions; create policy questions_read on public.questions for select using(is_published=true);
drop policy if exists attempts_own on public.attempts; create policy attempts_own on public.attempts for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists answers_own on public.attempt_answers; create policy answers_own on public.attempt_answers for all using(exists(select 1 from public.attempts a where a.id=attempt_id and a.user_id=auth.uid())) with check(exists(select 1 from public.attempts a where a.id=attempt_id and a.user_id=auth.uid()));

create or replace function public.submit_practice_answer(p_attempt_id uuid,p_question_id uuid,p_selected_answer text) returns boolean language plpgsql security definer set search_path=public as $$ declare v_correct boolean; begin if not exists(select 1 from attempts where id=p_attempt_id and user_id=auth.uid()) then raise exception 'Unauthorized attempt'; end if; select correct_answer=p_selected_answer into v_correct from questions where id=p_question_id and is_published=true; insert into attempt_answers(attempt_id,question_id,selected_answer,is_correct) values(p_attempt_id,p_question_id,p_selected_answer,coalesce(v_correct,false)) on conflict(attempt_id,question_id) do update set selected_answer=excluded.selected_answer,is_correct=excluded.is_correct,answered_at=now(); update attempts set correct_answers=(select count(*) from attempt_answers where attempt_id=p_attempt_id and is_correct), total_questions=(select count(*) from attempt_answers where attempt_id=p_attempt_id), score_percent=case when (select count(*) from attempt_answers where attempt_id=p_attempt_id)>0 then round(100.0*(select count(*) from attempt_answers where attempt_id=p_attempt_id and is_correct)/(select count(*) from attempt_answers where attempt_id=p_attempt_id),2) else 0 end where id=p_attempt_id; return coalesce(v_correct,false); end; $$;
grant execute on function public.submit_practice_answer(uuid,uuid,text) to authenticated;

insert into public.questions(exam,skill,level,prompt,passage,options,correct_answer,explanation) values
('TEF','reading','A2','Pourquoi Marie prend-elle le train ce matin ?','Marie habite à Hamilton. Ce matin, elle prend le train pour aller à Toronto où elle a un rendez-vous avec son médecin.','["Pour travailler","Pour voir son médecin","Pour faire des courses","Pour rendre visite à Paul"]','Pour voir son médecin','Le texte indique qu’elle va à Toronto pour un rendez-vous médical.'),
('TEF','reading','A2','À quelle heure commence la réunion ?','La réunion de l’équipe commence à neuf heures. Paul arrive dix minutes avant et prépare les documents.','["8 h 30","8 h 50","9 h 00","9 h 10"]','9 h 00','La réunion commence à neuf heures.'),
('TEF','reading','A2','Que doit acheter Julien ?','Julien va au supermarché après le travail. Il doit acheter du lait, du pain et des pommes pour le petit-déjeuner.','["Du fromage","Du riz","Du lait","Du café"]','Du lait','Le lait fait partie de sa liste.'),
('TEF','reading','B1','Pourquoi la bibliothèque change-t-elle ses horaires ?','À partir de lundi, la bibliothèque municipale ouvrira plus tôt le matin. Cette décision répond aux demandes des étudiants qui souhaitent étudier avant leurs cours.','["Pour réduire les coûts","Pour répondre aux étudiants","Pour fermer plus tôt","Pour organiser des concerts"]','Pour répondre aux étudiants','Le nouveau horaire répond aux demandes des étudiants.'),
('TEF','reading','B1','Quelle est la principale difficulté du projet ?','L’équipe a terminé la première partie du projet, mais elle rencontre encore des difficultés avec les données fournies par le client. Une réunion est prévue vendredi pour résoudre le problème.','["Le budget","Les données du client","Le calendrier","Le recrutement"]','Les données du client','Le texte identifie les données comme le problème restant.')
 on conflict do nothing;